/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (C) 2019 Marvell International Ltd.
 */
#ifndef _RTE_EVENTMODE_HELPER_H_
#define _RTE_EVENTMODE_HELPER_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <rte_compat.h>

/* Packet transfer mode of the application */
enum rte_eventmode_helper_pkt_transfer_mode {
	RTE_EVENTMODE_HELPER_PKT_TRANSFER_MODE_POLL = 0,
	RTE_EVENTMODE_HELPER_PKT_TRANSFER_MODE_EVENT,
};

struct rte_eventmode_helper_conf {
	enum rte_eventmode_helper_pkt_transfer_mode mode;
		/**< Packet transfer mode of the application */
	void *mode_params;
		/**< Mode specific parameters */
};

/* Common helper functions for command line parsing */

/**
 * Print event mode options list
 *
 */
void __rte_experimental
rte_eventmode_helper_print_options_list(void);

/**
 * Print event mode options description
 *
 */
void __rte_experimental
rte_eventmode_helper_print_options_description(void);

/**
 * Parse event mode arguments
 *
 * The application can call this function in it's argument parsing routine to
 * parse the event mode specific args and create the conf accordingly. This
 * function is to be executed on the MASTER lcore only.
 *
 * @param argc
 *   A non-negative value. If it is greater than 0, the array members
 *   for argv[0] through argv[argc] (non-inclusive) shall contain pointers
 *   to strings.
 * @param argv
 *   An array of strings. The contents of the array, as well as the strings
 *   which are pointed to by the array, may be modified by this function.
 * @return
 *   Configuration generated by parsing the event mode args.
 */
struct rte_eventmode_helper_conf *
rte_eventmode_helper_parse_args(int argc, char **argv);

#ifdef __cplusplus
}
#endif

#endif /* _RTE_EVENTMODE_HELPER_H_ */
