# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2020 Intel Corporation.

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-$(CONFIG_RTE_LIBRTE_MULTI_FN_COMMON) += multi_fn

include $(RTE_SDK)/mk/rte.subdir.mk
