/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2019 Intel Corporation
 */

TEST_EXPAND(gcm_test_case_1, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_2, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_3, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_4, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_5, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_6, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_7, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_8, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_192_1, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_192_2, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_192_3, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_192_4, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_192_5, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_192_6, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_192_7, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_256_1, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_256_2, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_256_3, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_256_4, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_256_5, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_256_6, SGL_ONE_SEG)
TEST_EXPAND(gcm_test_case_256_7, SGL_ONE_SEG)

TEST_EXPAND(gcm_test_case_1, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_2, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_3, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_4, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_5, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_6, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_7, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_8, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_192_1, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_192_2, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_192_3, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_192_4, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_192_5, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_192_6, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_192_7, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_256_1, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_256_2, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_256_3, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_256_4, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_256_5, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_256_6, SGL_MAX_SEG)
TEST_EXPAND(gcm_test_case_256_7, SGL_MAX_SEG)
